### PR TITLE
New source https://www.chickengege.org/

### PR DESCRIPTION
**Pull request by idMysteries**
https://github.com/dipu-bd/lightnovel-crawler/issues/644

Some chapters are password protected. I don't know how to bypass it.

### CODE REVIEW

**Comment by idMysteries** [comment]
@dipu-bd bad_css does not work for some reason. "div.class" not removed.

**Comment by dipu-bd** [comment]
You are using `div.go-night-color`. it will remove all div tags with that class name. But I saw other tags containing that class.
image

just pass `.go-night-color`

**Comment by idMysteries** [comment]
Why you don't merge it? I don't use .go-night-color here...
>  it will remove all div tags with that class name. 
No, it doesn't remove the div tag!

**Comment by idMysteries** [comment]
image

**Comment by dipu-bd** [comment]
> No, it doesn't remove the div tag!

interesting.. this should not happen. either it is BeautifulSoup bug or there could be something you are missing

**Pull request merged**
